import { createClient, createServiceClient } from "@/lib/supabase/server";
import { NextRequest, NextResponse } from "next/server";

export const maxDuration = 60;

// Buckets that files may be uploaded into. The actual filename inside the
// bucket is generated by the server (unique, timestamped) — never trust the
// client-provided name.
const ALLOWED_BUCKETS = new Set(["materials", "assignments", "submissions", "avatars"]);

const MAX_FILE_SIZE = 50 * 1024 * 1024; // 50MB, matches the client-side limits

/**
 * POST /api/uploads
 * multipart/form-data: { file: File, bucket: string }
 *
 * Server-side upload proxy. Storage RLS policies are a project-wide
 * dependency — when they are missing (e.g. after recreating the Supabase
 * project) every browser upload fails with:
 *   403 "new row violates row-level security policy"
 * Uploading with the service client from the server removes that dependency
 * while still enforcing role checks in application code.
 */
export async function POST(request: NextRequest) {
  try {
    const supabase = createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Students may only upload into submissions; teachers anywhere.
    const { data: profile } = await supabase
      .from("users")
      .select("role")
      .eq("id", user.id)
      .single();

    const role = profile?.role ?? "student";

    const formData = await request.formData();
    const file = formData.get("file") as File | null;
    const bucket = String(formData.get("bucket") || "");

    if (!file || !bucket) {
      return NextResponse.json({ error: "Missing file or bucket" }, { status: 400 });
    }

    if (!ALLOWED_BUCKETS.has(bucket)) {
      return NextResponse.json({ error: "Invalid bucket" }, { status: 400 });
    }

    if (role !== "teacher" && bucket !== "submissions") {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    if (file.size > MAX_FILE_SIZE) {
      return NextResponse.json({ error: "File too large. Max 50MB" }, { status: 400 });
    }

    const fileExt = file.name.split(".").pop() || "bin";
    const fileName = `${Date.now()}-${Math.random().toString(36).substring(7)}.${fileExt}`;

    // Path conventions the rest of the app already relies on:
    // - assignments bucket → shared/<file>
    // - materials bucket   → <classId>/<file> when classId is provided
    let filePath = fileName;
    if (bucket === "assignments") {
      filePath = `shared/${fileName}`;
    } else if (bucket === "materials") {
      const classId = String(formData.get("classId") || "");
      filePath = classId ? `${classId}/${fileName}` : fileName;
    }

    const bytes = Buffer.from(await file.arrayBuffer());

    // Service client bypasses storage RLS on purpose — authz was checked above.
    const admin = createServiceClient();
    const { error: uploadError } = await admin.storage
      .from(bucket)
      .upload(filePath, bytes, {
        contentType: file.type || "application/octet-stream",
        cacheControl: "3600",
        upsert: false,
      });

    if (uploadError) {
      console.error("[/api/uploads] storage error:", uploadError.message);
      return NextResponse.json({ error: uploadError.message }, { status: 500 });
    }

    const { data: urlData } = admin.storage.from(bucket).getPublicUrl(filePath);

    return NextResponse.json({ success: true, path: filePath, url: urlData.publicUrl });
  } catch (err: any) {
    console.error("[/api/uploads] unexpected error:", err?.message || err);
    return NextResponse.json({ error: err?.message || "Upload failed" }, { status: 500 });
  }
}
